version: '3'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8090:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=_mysql
    restart: always
    depends_on:
      - mysql
    networks:
      - main-network
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    volumes:
      - "./.docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    ports:
      - "8989:3306"
    networks:
      - main-network
  redis:
    image: "redis:alpine"
    container_name: redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - 6379:6379
    env_file:
      - ".env"
    volumes:
      - './.docker/redis:/redis'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: always
    networks:
      - main-network
networks:
  main-network:
    driver: bridge

